### ISSUE TITLE
Add feature for encrypted notes storage

### ISSUE THREAD

**Issue by jityong** [AY1920S1-CS2103T-F11-3/main#24]
- [x] Add / create notes 

- [x] Read stored  notes

- [x] Update existing notes

- [x] Delete notes
