### ISSUE TITLE
Add feature for password security report

### ISSUE THREAD

**Issue by eejian97** [AY1920S1-CS2103T-F11-3/main#27]
- [x] Show account sharing same password
- [x] Show accounts using common passwords 
- [x] Show accounts with username in password
- [x] Show accounts with organisation in password 
- [x] Show accounts less than required minimum length
